app = "ollama-demo"
primary_region = "ord"
vm.size = "a100-40gb"

[build]
image = "ollama/ollama:latest"

[[mounts]]
source = "ollama"
destination = "/root/.ollama"

[http_service]
internal_port = 11434
force_https = true
