app = "ollama-demo"
primary_region = "ord"

[build]
image = "ollama/ollama:latest"

[[mounts]]
source = "ollama"
destination = "/root/.ollama"

[[compute]]
size = "a100-40gb"

[http_service]
internal_port = 11434
